"""
LLM Clinical Analysis Engine — Day 3
=======================================
Generates structured clinical reasoning chains for each abnormal biomarker
and cross-biomarker patterns. Uses RAG-retrieved context as grounding.

Supports multiple backends:
- Anthropic Claude API (primary)
- OpenAI API (fallback)
- Local/offline mode (template-based, no API needed)
"""

import os
import json
import re
from dataclasses import dataclass, field, asdict
from typing import Optional

from .report_analyzer import ReportAnalyzer, EnrichedReport, BiomarkerAnalysis


# ================================================================
# DATA MODELS
# ================================================================

@dataclass
class BiomarkerInterpretation:
    test_name: str
    canonical_name: str
    value: float
    unit: str
    flag: str
    deviation_pct: float
    interpretation_band: str
    clinical_significance: str    # What this abnormality means
    possible_causes: list[str]    # Ranked list of likely causes
    recommended_actions: list[str] # What the patient/doctor should do
    urgency: str                  # routine / soon / urgent / emergency
    sources: list[str]            # Citations from RAG


@dataclass
class PatternInterpretation:
    pattern_name: str
    involved_biomarkers: list[str]
    clinical_reasoning: str       # Chain-of-thought explanation
    diagnosis_suggestion: str     # What this pattern points to
    recommended_workup: list[str] # Additional tests to confirm
    sources: list[str]


@dataclass
class ClinicalReport:
    patient_name: str
    patient_age: str
    patient_sex: str
    lab_name: str
    report_date: str
    total_tests: int
    abnormal_count: int
    critical_count: int
    executive_summary: str
    biomarker_interpretations: list[BiomarkerInterpretation] = field(default_factory=list)
    pattern_interpretations: list[PatternInterpretation] = field(default_factory=list)
    lifestyle_recommendations: list[str] = field(default_factory=list)
    follow_up_tests: list[str] = field(default_factory=list)
    disclaimer: str = (
        "This analysis is generated by an AI system for educational and informational purposes only. "
        "It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
        "Always consult a qualified healthcare provider for interpretation of your results."
    )


# ================================================================
# PROMPT TEMPLATES
# ================================================================

SYSTEM_PROMPT = """You are a clinical laboratory medicine expert assistant. You analyze lab report biomarkers
and provide evidence-based interpretations grounded in medical literature.

Rules:
1. Be precise and cite sources for every claim.
2. Use clinical reasoning chains: observation → mechanism → differential → recommendation.
3. Consider the patient's complete panel — don't interpret biomarkers in isolation.
4. Classify urgency: routine (recheck in 3-6 months), soon (see doctor within 2-4 weeks),
   urgent (see doctor within 1 week), emergency (immediate medical attention).
5. Always note that this is for educational purposes and not medical advice.
6. For Indian patients, consider India-specific prevalence data and dietary patterns.
7. Output valid JSON only — no markdown, no preamble."""

BIOMARKER_PROMPT_TEMPLATE = """Analyze this abnormal biomarker for patient {name} ({age}, {sex}):

Test: {test_name} ({canonical_name})
Value: {value} {unit}
Flag: {flag} (deviation: {deviation_pct}% from normal range)
Interpretation band: {band}

RAG context (from medical literature):
{rag_context}

Other abnormal biomarkers in this patient's panel:
{other_abnormals}

Respond with ONLY this JSON (no markdown):
{{
  "clinical_significance": "2-3 sentence explanation of what this means clinically",
  "possible_causes": ["cause1 (most likely)", "cause2", "cause3"],
  "recommended_actions": ["action1", "action2"],
  "urgency": "routine|soon|urgent|emergency"
}}"""

PATTERN_PROMPT_TEMPLATE = """Analyze this combined biomarker pattern for patient {name} ({age}, {sex}):

Abnormal biomarkers involved:
{biomarker_list}

RAG context (combined pattern analysis):
{rag_context}

Full abnormal panel:
{all_abnormals}

Provide a clinical reasoning chain. Respond with ONLY this JSON (no markdown):
{{
  "pattern_name": "short name for this pattern",
  "clinical_reasoning": "Step-by-step reasoning chain: observation → mechanism → implication",
  "diagnosis_suggestion": "What this pattern most likely indicates",
  "recommended_workup": ["additional test 1", "additional test 2"]
}}"""

SUMMARY_PROMPT_TEMPLATE = """Generate an executive summary and recommendations for this patient's complete lab panel.

Patient: {name}, {age}, {sex}
Lab: {lab_name}

Abnormal findings ({abnormal_count} of {total_tests} tests):
{abnormal_summary}

Pattern analyses found:
{pattern_summary}

Respond with ONLY this JSON (no markdown):
{{
  "executive_summary": "3-4 sentence overview of the most important findings and their clinical significance",
  "lifestyle_recommendations": ["recommendation1", "recommendation2", "recommendation3", "recommendation4"],
  "follow_up_tests": ["test1 (reason)", "test2 (reason)", "test3 (reason)"]
}}"""


# ================================================================
# LLM BACKENDS
# ================================================================

def _call_anthropic(system: str, prompt: str) -> str:
    """Call Anthropic Claude API."""
    try:
        import anthropic
        client = anthropic.Anthropic()
        response = client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=1024,
            system=system,
            messages=[{"role": "user", "content": prompt}]
        )
        return response.content[0].text
    except Exception as e:
        raise RuntimeError(f"Anthropic API error: {e}")


def _call_openai(system: str, prompt: str) -> str:
    """Call OpenAI API."""
    try:
        import openai
        client = openai.OpenAI()
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": system},
                {"role": "user", "content": prompt}
            ],
            max_tokens=1024,
            temperature=0.3,
        )
        return response.choices[0].message.content
    except Exception as e:
        raise RuntimeError(f"OpenAI API error: {e}")


def _parse_json_response(text: str) -> dict:
    """Parse JSON from LLM response, handling markdown fences."""
    cleaned = text.strip()
    cleaned = re.sub(r'^```(?:json)?\s*', '', cleaned)
    cleaned = re.sub(r'\s*```$', '', cleaned)
    return json.loads(cleaned)


# ================================================================
# LOCAL/OFFLINE ANALYSIS ENGINE (no API needed)
# ================================================================

class LocalAnalysisEngine:
    """Template-based clinical reasoning — works fully offline."""

    # Urgency rules based on deviation
    URGENCY_RULES = {
        (0, 10): "routine",
        (10, 30): "routine",
        (30, 50): "soon",
        (50, 100): "soon",
        (100, 999): "urgent",
    }

    def _get_urgency(self, deviation: float, flag: str) -> str:
        if "CRITICAL" in flag:
            return "emergency"
        for (lo, hi), urgency in self.URGENCY_RULES.items():
            if lo <= abs(deviation) < hi:
                return urgency
        return "routine"

    def interpret_biomarker(self, ba: BiomarkerAnalysis, other_abnormals: list[str],
                            patient_sex: str) -> BiomarkerInterpretation:
        """Generate interpretation from RAG context using template reasoning."""
        # Extract info from top RAG result
        rag_top = ba.rag_interpretations[0] if ba.rag_interpretations else {}
        rag_content = rag_top.get("content", "")
        rag_source = rag_top.get("source", "Clinical reference")

        # Extract causes from RAG content
        causes = self._extract_causes(rag_content, ba.canonical_name, ba.flag)
        actions = self._extract_actions(rag_content, ba.canonical_name, ba.flag, ba.interpretation_band)
        significance = self._build_significance(ba, rag_content, patient_sex)
        urgency = self._get_urgency(ba.deviation_pct, ba.flag)

        sources = [rag_top.get("source", "")] if rag_top else []
        sources = [s for s in sources if s]

        return BiomarkerInterpretation(
            test_name=ba.test_name,
            canonical_name=ba.canonical_name,
            value=ba.value,
            unit=ba.unit,
            flag=ba.flag,
            deviation_pct=ba.deviation_pct,
            interpretation_band=ba.interpretation_band,
            clinical_significance=significance,
            possible_causes=causes[:4],
            recommended_actions=actions[:3],
            urgency=urgency,
            sources=sources,
        )

    def _build_significance(self, ba: BiomarkerAnalysis, rag_content: str, sex: str) -> str:
        direction = "elevated" if "HIGH" in ba.flag else "below normal"
        band_note = f" This falls in the '{ba.interpretation_band}' range." if ba.interpretation_band else ""

        # Extract first meaningful sentence from RAG
        sentences = [s.strip() for s in rag_content.split('.') if len(s.strip()) > 30]
        rag_sentence = sentences[1] if len(sentences) > 1 else ""

        return (
            f"{ba.test_name} at {ba.value} {ba.unit} is {direction} "
            f"({ba.deviation_pct}% outside reference range).{band_note} "
            f"{rag_sentence}."
        )

    def _extract_causes(self, rag_content: str, name: str, flag: str) -> list[str]:
        """Extract possible causes from RAG content using pattern matching."""
        causes_map = {
            "haemoglobin": {
                "LOW": ["Iron deficiency anaemia (most common globally)", "Chronic disease",
                         "B12/folate deficiency", "Thalassemia trait"],
            },
            "total_wbc_count": {
                "HIGH": ["Bacterial infection (most common)", "Inflammatory response",
                         "Stress/exercise", "Corticosteroid use"],
            },
            "esr": {
                "HIGH": ["Active infection or inflammation", "Autoimmune disease",
                         "Underlying anaemia", "Chronic kidney disease"],
            },
            "total_cholesterol": {
                "HIGH": ["Dietary factors (high saturated fat)", "Genetic predisposition",
                         "Hypothyroidism (secondary cause)", "Sedentary lifestyle"],
            },
            "triglycerides": {
                "HIGH": ["Obesity/metabolic syndrome", "High refined carbohydrate diet",
                         "Uncontrolled diabetes", "Excessive alcohol intake"],
            },
            "hdl_cholesterol": {
                "LOW": ["Sedentary lifestyle", "Smoking", "Metabolic syndrome",
                        "High carbohydrate diet"],
            },
            "ldl_cholesterol": {
                "HIGH": ["Dietary saturated fat", "Genetic factors",
                         "Hypothyroidism (check TSH)", "Obesity"],
            },
            "sgot_ast": {
                "HIGH": ["Non-alcoholic fatty liver disease (NAFLD)", "Alcohol-related liver injury",
                         "Viral hepatitis", "Medication-induced"],
            },
            "sgpt_alt": {
                "HIGH": ["NAFLD (most common cause globally)", "Viral hepatitis B/C",
                         "Drug-induced liver injury", "Autoimmune hepatitis"],
            },
            "ggt": {
                "HIGH": ["Alcohol use (most sensitive marker)", "NAFLD/metabolic syndrome",
                         "Medications (phenytoin, carbamazepine)", "Cholestatic disease"],
            },
            "tsh": {
                "HIGH": ["Hashimoto thyroiditis (most common)", "Iodine deficiency",
                         "Subclinical hypothyroidism", "Post-thyroiditis recovery"],
            },
            "fasting_blood_sugar": {
                "HIGH": ["Prediabetes / impaired fasting glucose", "Early type 2 diabetes",
                         "Stress hyperglycaemia", "Medication effect (steroids)"],
            },
            "hba1c": {
                "HIGH": ["Prediabetes (5.7-6.4%)", "Type 2 diabetes (≥6.5%)",
                         "Iron deficiency (falsely elevated)", "Chronic hyperglycaemia"],
            },
            "vitamin_d": {
                "LOW": ["Indoor lifestyle / limited sun exposure", "Dark skin pigmentation",
                         "Vegetarian diet", "Malabsorption"],
            },
            "vitamin_b12": {
                "LOW": ["Vegetarian/vegan diet (most common in India)", "Pernicious anaemia",
                         "H. pylori infection", "Metformin or PPI use"],
            },
            "iron_serum": {
                "LOW": ["Dietary iron deficiency", "Chronic blood loss",
                         "Malabsorption (celiac)", "Increased demand (growth, pregnancy)"],
            },
            "ferritin": {
                "LOW": ["Iron deficiency (most specific marker)", "Chronic blood loss",
                         "Vegetarian diet with low iron intake", "Malabsorption"],
            },
            "tibc": {
                "HIGH": ["Iron deficiency (compensatory increase)", "Pregnancy",
                         "Chronic blood loss", "Oral contraceptive use"],
            },
            "transferrin_saturation": {
                "LOW": ["Iron deficiency anaemia", "Chronic disease with iron sequestration",
                         "Dietary insufficiency", "Chronic blood loss"],
            },
            "uric_acid": {
                "HIGH": ["Purine-rich diet (red meat, seafood)", "Obesity/metabolic syndrome",
                         "Chronic kidney disease", "Diuretic medications"],
            },
            "total_bilirubin": {
                "HIGH": ["Gilbert syndrome (benign, most common)", "Hemolysis",
                         "Hepatocellular disease", "Cholestasis"],
            },
            "direct_bilirubin": {
                "HIGH": ["Hepatocellular disease", "Cholestasis (biliary obstruction)",
                         "Drug-induced liver injury", "Sepsis"],
            },
            "packed_cell_volume": {
                "LOW": ["Iron deficiency anaemia", "Chronic disease", "Acute blood loss", "B12/folate deficiency"],
                "HIGH": ["Dehydration", "Polycythaemia vera", "Chronic hypoxia", "Smoking"],
            },
            "rdw": {
                "HIGH": ["Iron deficiency anaemia (most common)", "B12/folate deficiency",
                         "Mixed nutritional deficiency", "Early iron deficiency"],
            },
            "neutrophils": {
                "HIGH": ["Bacterial infection", "Acute inflammation", "Stress response", "Corticosteroid use"],
                "LOW": ["Viral infection", "Drug-induced neutropenia", "Autoimmune condition", "Bone marrow suppression"],
            },
            "free_t3": {
                "LOW": ["Hypothyroidism", "Sick euthyroid syndrome (non-thyroidal illness)",
                         "Amiodarone use", "Severe caloric restriction"],
            },
            "free_t4": {
                "LOW": ["Primary hypothyroidism (with high TSH)", "Central hypothyroidism (with normal/low TSH)",
                         "Severe illness (sick euthyroid)", "Medication effect (phenytoin, carbamazepine)"],
            },
            "blood_urea": {
                "HIGH": ["High protein diet", "Dehydration (pre-renal)",
                         "Gastrointestinal bleeding", "Catabolic state / fever"],
                "LOW": ["Low protein diet", "Severe liver disease", "Overhydration"],
            },
        }

        key = name.lower()
        flag_key = "HIGH" if "HIGH" in flag else "LOW"
        if key in causes_map and flag_key in causes_map[key]:
            return causes_map[key][flag_key]
        return ["Further clinical evaluation needed"]

    def _extract_actions(self, rag_content: str, name: str, flag: str, band: str) -> list[str]:
        """Generate recommended actions based on biomarker context."""
        actions_map = {
            "haemoglobin": ["Check iron studies (ferritin, TIBC, transferrin saturation)", "Peripheral blood smear", "Consider dietary iron supplementation"],
            "total_wbc_count": ["Correlate with clinical symptoms (fever, infection signs)", "Repeat CBC after 2 weeks if no acute illness", "Consider CRP for acute inflammation assessment"],
            "esr": ["Check CRP for acute-phase correlation", "Evaluate for underlying infection or autoimmune condition", "Repeat in 4-6 weeks if no clear cause"],
            "total_cholesterol": ["Lifestyle modification: reduce saturated fat, increase fibre", "Check thyroid function before starting statins", "Recheck fasting lipid panel in 3 months"],
            "triglycerides": ["Reduce refined carbohydrates and alcohol", "Increase physical activity (150 min/week)", "Recheck fasting lipids after lifestyle changes"],
            "hdl_cholesterol": ["Regular aerobic exercise (raises HDL 5-10%)", "Smoking cessation if applicable", "Mediterranean diet pattern"],
            "ldl_cholesterol": ["Dietary modification: <7% calories from saturated fat", "Exercise 150 min/week moderate intensity", "Assess cardiovascular risk (ASCVD calculator)"],
            "sgot_ast": ["Hepatitis B/C serology", "Abdominal ultrasound", "Review medications and alcohol history"],
            "sgpt_alt": ["Hepatitis B surface antigen and anti-HCV", "Liver ultrasound for fatty liver assessment", "Review all current medications"],
            "ggt": ["Detailed alcohol history", "Liver ultrasound", "Correlate with ALP to differentiate cholestatic vs hepatocellular"],
            "tsh": ["Anti-TPO antibodies to check for Hashimoto's", "Recheck TSH + Free T4 in 6-8 weeks", "Endocrinology referral if TSH >10"],
            "fasting_blood_sugar": ["Repeat FBS to confirm", "Oral glucose tolerance test (OGTT) if borderline", "Lifestyle modification: 7% weight loss + 150 min/week exercise"],
            "hba1c": ["Confirm with repeat HbA1c in 3 months", "Dietary counselling: reduce refined carbohydrates", "Screen for complications if diabetic range"],
            "vitamin_d": ["Cholecalciferol 60,000 IU weekly x 8 weeks (loading)", "Maintenance: 1000-2000 IU daily", "Recheck 25-OH Vitamin D after 3 months"],
            "vitamin_b12": ["Oral B12 1000-2000 µg daily if mild deficiency", "IM cyanocobalamin if severe (<150 pg/mL) or neurological symptoms", "Assess dietary sources (vegetarian counselling)"],
            "iron_serum": ["Oral ferrous sulfate 325 mg with Vitamin C on empty stomach", "Investigate cause of iron loss", "Recheck iron studies in 3 months"],
            "ferritin": ["Start oral iron supplementation", "Rule out chronic blood loss (stool occult blood)", "Recheck ferritin after 3 months of supplementation"],
            "tibc": ["Correlate with ferritin and transferrin saturation", "Initiate iron supplementation", "Investigate underlying cause of iron deficiency"],
            "transferrin_saturation": ["Start iron supplementation", "Dietary counselling: iron-rich foods with Vitamin C", "Follow-up iron panel in 3 months"],
            "uric_acid": ["Dietary modification: reduce purines, limit alcohol", "Adequate hydration (2-3 L/day)", "Monitor for gout symptoms (joint pain, swelling)"],
            "total_bilirubin": ["Check direct vs indirect bilirubin ratio", "If isolated unconjugated elevation: consider Gilbert syndrome", "Liver ultrasound if conjugated bilirubin elevated"],
            "direct_bilirubin": ["Liver ultrasound to rule out biliary obstruction", "Hepatitis serology", "Review medications for hepatotoxicity"],
            "packed_cell_volume": ["Correlate with haemoglobin and RBC count", "Check hydration status", "Peripheral blood smear if polycythaemia suspected"],
            "rdw": ["Check iron studies and B12/folate levels", "Peripheral blood smear for RBC morphology", "Correlate with MCV for anaemia classification"],
            "neutrophils": ["Complete infection screen if elevated", "Repeat CBC after 2 weeks", "Check peripheral smear if significantly abnormal"],
            "free_t3": ["Check TSH and Free T4 for thyroid status", "Rule out non-thyroidal illness if hospitalized", "Endocrinology referral if persistently low"],
            "free_t4": ["Check TSH — high TSH confirms primary hypothyroidism", "Anti-TPO antibodies for autoimmune cause", "Start levothyroxine if overt hypothyroidism confirmed"],
            "blood_urea": ["Check serum creatinine and eGFR for renal function", "Assess hydration status", "Review dietary protein intake"],
        }

        key = name.lower()
        if key in actions_map:
            return actions_map[key]
        return ["Consult physician for further evaluation", "Repeat test to confirm"]

    def analyze_patterns(self, enriched: EnrichedReport) -> list[PatternInterpretation]:
        """Generate pattern interpretations from combined analysis."""
        patterns = []

        for cp in enriched.combined_patterns:
            patterns.append(PatternInterpretation(
                pattern_name=cp.pattern_title,
                involved_biomarkers=cp.relevant_biomarkers,
                clinical_reasoning=cp.content[:400],
                diagnosis_suggestion=cp.pattern_title.split("—")[0].strip() if "—" in cp.pattern_title else cp.pattern_title,
                recommended_workup=self._get_workup_for_pattern(cp.pattern_title),
                sources=[cp.source],
            ))

        return patterns

    def _get_workup_for_pattern(self, pattern_title: str) -> list[str]:
        title_lower = pattern_title.lower()
        if "iron" in title_lower and "b12" in title_lower:
            return ["Peripheral blood smear (dimorphic picture)", "Reticulocyte count",
                    "Methylmalonic acid + homocysteine (if B12 borderline)"]
        elif "metabolic syndrome" in title_lower:
            return ["Fasting insulin (HOMA-IR)", "Waist circumference measurement",
                    "Blood pressure check", "Liver ultrasound for NAFLD"]
        elif "hashimoto" in title_lower or "thyroid" in title_lower and "vitamin d" in title_lower:
            return ["Anti-TPO antibodies (if not already done)", "Thyroid ultrasound",
                    "Vitamin D 25-OH recheck after 3 months supplementation"]
        elif "hypothyroidism" in title_lower and "dyslipidemia" in title_lower:
            return ["Recheck lipid panel after 3 months of thyroid treatment",
                    "Do NOT start statins until thyroid is normalized",
                    "Free T4 + TSH monitoring every 6-8 weeks"]
        elif "nafld" in title_lower or "fatty liver" in title_lower:
            return ["Liver ultrasound", "FIB-4 score for fibrosis staging",
                    "Hepatitis B/C serology to exclude viral cause"]
        return ["Further clinical evaluation", "Specialist referral as needed"]

    def generate_summary(self, enriched: EnrichedReport,
                         interpretations: list[BiomarkerInterpretation],
                         patterns: list[PatternInterpretation]) -> tuple[str, list[str], list[str]]:
        """Generate executive summary, lifestyle recs, and follow-up tests."""

        # Build summary from most significant findings
        urgent = [i for i in interpretations if i.urgency in ("urgent", "emergency")]
        soon = [i for i in interpretations if i.urgency == "soon"]

        summary_parts = []
        summary_parts.append(
            f"Analysis of {enriched.total_tests} biomarkers reveals "
            f"{enriched.abnormal_count} abnormal values across multiple organ systems."
        )

        # Key findings by category
        categories = {}
        for i in interpretations:
            cat = self._get_category(i.canonical_name)
            if cat not in categories:
                categories[cat] = []
            categories[cat].append(i)

        for cat, items in categories.items():
            names = ", ".join(i.test_name.split("(")[0].strip() for i in items[:3])
            summary_parts.append(f"{cat}: {names} abnormal.")

        if patterns:
            pattern_names = [p.pattern_name.split("—")[0].strip() for p in patterns[:3]]
            summary_parts.append(f"Cross-biomarker patterns identified: {'; '.join(pattern_names)}.")

        if urgent:
            summary_parts.append(f"PRIORITY: {len(urgent)} value(s) require prompt medical attention.")

        executive_summary = " ".join(summary_parts)

        # Lifestyle recommendations (deduplicated from individual recs)
        lifestyle = []
        all_actions = set()
        for i in interpretations:
            for a in i.recommended_actions:
                if a.lower() not in all_actions and any(kw in a.lower() for kw in
                    ["lifestyle", "diet", "exercise", "weight", "reduce", "increase", "smoking", "alcohol", "hydrat", "sun"]):
                    all_actions.add(a.lower())
                    lifestyle.append(a)

        if not lifestyle:
            lifestyle = [
                "Balanced diet with adequate protein, iron, and B12 sources",
                "Regular exercise: 150 minutes/week moderate intensity",
                "Adequate hydration: 2-3 litres/day",
                "Annual health check-up with complete blood panel",
            ]

        # Follow-up tests (deduplicated)
        follow_up = []
        seen = set()
        for i in interpretations:
            for a in i.recommended_actions:
                key = a.lower()[:30]
                if key not in seen and any(kw in a.lower() for kw in
                    ["check", "test", "serology", "ultrasound", "recheck", "repeat", "screen", "referral"]):
                    seen.add(key)
                    follow_up.append(a)

        for p in patterns:
            for w in p.recommended_workup:
                key = w.lower()[:30]
                if key not in seen:
                    seen.add(key)
                    follow_up.append(w)

        return executive_summary, lifestyle[:6], follow_up[:10]

    def _get_category(self, canonical_name: str) -> str:
        cat_map = {
            "haemoglobin": "Blood Count", "total_wbc_count": "Blood Count", "esr": "Blood Count",
            "rdw": "Blood Count", "packed_cell_volume": "Blood Count", "neutrophils": "Blood Count",
            "total_cholesterol": "Lipids", "triglycerides": "Lipids", "hdl_cholesterol": "Lipids",
            "ldl_cholesterol": "Lipids", "vldl_cholesterol": "Lipids",
            "sgot_ast": "Liver", "sgpt_alt": "Liver", "ggt": "Liver",
            "total_bilirubin": "Liver", "direct_bilirubin": "Liver",
            "tsh": "Thyroid", "free_t3": "Thyroid", "free_t4": "Thyroid",
            "fasting_blood_sugar": "Diabetes", "hba1c": "Diabetes",
            "vitamin_d": "Vitamins/Minerals", "vitamin_b12": "Vitamins/Minerals",
            "iron_serum": "Iron Studies", "ferritin": "Iron Studies",
            "tibc": "Iron Studies", "transferrin_saturation": "Iron Studies",
            "uric_acid": "Kidney",
        }
        return cat_map.get(canonical_name, "Other")


# ================================================================
# MAIN ANALYSIS ENGINE
# ================================================================

class ClinicalAnalysisEngine:
    """Orchestrates the full clinical analysis pipeline."""

    def __init__(self, mode: str = "local"):
        """
        Args:
            mode: "local" (offline template-based), "anthropic", or "openai"
        """
        self.mode = mode
        self.report_analyzer = ReportAnalyzer()
        self.local_engine = LocalAnalysisEngine()

    def analyze_report(self, pdf_path: str) -> ClinicalReport:
        """Full pipeline: PDF → Extract → RAG → LLM Analysis → Clinical Report."""

        # Step 1: Extract + RAG enrich
        enriched = self.report_analyzer.analyze(pdf_path)

        # Step 2: Generate biomarker interpretations
        other_abnormals = [
            f"{ba.test_name}: {ba.value} {ba.unit} ({ba.flag})"
            for ba in enriched.biomarker_analyses
        ]

        interpretations = []
        for ba in enriched.biomarker_analyses:
            if self.mode == "local":
                interp = self.local_engine.interpret_biomarker(
                    ba, other_abnormals, enriched.patient_sex
                )
            else:
                interp = self._llm_interpret_biomarker(ba, other_abnormals, enriched)

            interpretations.append(interp)

        # Step 3: Pattern analysis
        if self.mode == "local":
            patterns = self.local_engine.analyze_patterns(enriched)
        else:
            patterns = self._llm_analyze_patterns(enriched)

        # Step 4: Executive summary
        if self.mode == "local":
            summary, lifestyle, followup = self.local_engine.generate_summary(
                enriched, interpretations, patterns
            )
        else:
            summary, lifestyle, followup = self._llm_generate_summary(
                enriched, interpretations, patterns
            )

        return ClinicalReport(
            patient_name=enriched.patient_name,
            patient_age=enriched.patient_age,
            patient_sex=enriched.patient_sex,
            lab_name=enriched.lab_name,
            report_date="",
            total_tests=enriched.total_tests,
            abnormal_count=enriched.abnormal_count,
            critical_count=enriched.critical_count,
            executive_summary=summary,
            biomarker_interpretations=interpretations,
            pattern_interpretations=patterns,
            lifestyle_recommendations=lifestyle,
            follow_up_tests=followup,
        )

    def _llm_interpret_biomarker(self, ba: BiomarkerAnalysis,
                                  other_abnormals: list[str],
                                  enriched: EnrichedReport) -> BiomarkerInterpretation:
        """Use LLM API for biomarker interpretation."""
        rag_context = "\n".join(
            f"- {r['title']}: {r['content'][:300]}\n  Source: {r['source']}"
            for r in ba.rag_interpretations[:2]
        ) or "No specific RAG context available."

        prompt = BIOMARKER_PROMPT_TEMPLATE.format(
            name=enriched.patient_name, age=enriched.patient_age, sex=enriched.patient_sex,
            test_name=ba.test_name, canonical_name=ba.canonical_name,
            value=ba.value, unit=ba.unit, flag=ba.flag,
            deviation_pct=ba.deviation_pct, band=ba.interpretation_band or "N/A",
            rag_context=rag_context,
            other_abnormals="\n".join(f"  - {o}" for o in other_abnormals[:10]),
        )

        try:
            call_fn = _call_anthropic if self.mode == "anthropic" else _call_openai
            response = call_fn(SYSTEM_PROMPT, prompt)
            data = _parse_json_response(response)

            sources = [r.get("source", "") for r in ba.rag_interpretations[:2]]

            return BiomarkerInterpretation(
                test_name=ba.test_name, canonical_name=ba.canonical_name,
                value=ba.value, unit=ba.unit, flag=ba.flag,
                deviation_pct=ba.deviation_pct, interpretation_band=ba.interpretation_band,
                clinical_significance=data.get("clinical_significance", ""),
                possible_causes=data.get("possible_causes", []),
                recommended_actions=data.get("recommended_actions", []),
                urgency=data.get("urgency", "routine"),
                sources=sources,
            )
        except Exception:
            # Fallback to local
            return self.local_engine.interpret_biomarker(ba, other_abnormals, enriched.patient_sex)

    def _llm_analyze_patterns(self, enriched: EnrichedReport) -> list[PatternInterpretation]:
        """LLM-based pattern analysis (fallback to local)."""
        return self.local_engine.analyze_patterns(enriched)

    def _llm_generate_summary(self, enriched, interpretations, patterns):
        """LLM-based summary (fallback to local)."""
        return self.local_engine.generate_summary(enriched, interpretations, patterns)


# ================================================================
# OUTPUT FORMATTING
# ================================================================

def format_clinical_report(report: ClinicalReport) -> str:
    """Format the clinical report for display."""
    lines = []
    lines.append("=" * 72)
    lines.append("  MEDSCAN AI — CLINICAL ANALYSIS REPORT")
    lines.append("=" * 72)

    lines.append(f"\n  Patient: {report.patient_name}")
    lines.append(f"  Age/Sex: {report.patient_age} / {report.patient_sex}")
    lines.append(f"  Lab: {report.lab_name}")
    lines.append(f"  Panel: {report.total_tests} tests | {report.abnormal_count} abnormal | {report.critical_count} critical")

    lines.append(f"\n{'─' * 72}")
    lines.append(f"  EXECUTIVE SUMMARY")
    lines.append(f"{'─' * 72}")
    lines.append(f"  {report.executive_summary}")

    lines.append(f"\n{'─' * 72}")
    lines.append(f"  BIOMARKER INTERPRETATIONS ({len(report.biomarker_interpretations)})")
    lines.append(f"{'─' * 72}")

    for i, bi in enumerate(report.biomarker_interpretations, 1):
        icon = "🔺" if "HIGH" in bi.flag else "🔻"
        urg_icon = {"routine": "🟢", "soon": "🟡", "urgent": "🟠", "emergency": "🔴"}.get(bi.urgency, "⚪")

        lines.append(f"\n  {icon} {i}. {bi.test_name}: {bi.value} {bi.unit} [{bi.flag}] {urg_icon} {bi.urgency.upper()}")
        lines.append(f"     {bi.clinical_significance}")
        lines.append(f"     Possible causes: {' | '.join(bi.possible_causes[:3])}")
        lines.append(f"     Actions: {' | '.join(bi.recommended_actions[:2])}")
        if bi.sources:
            lines.append(f"     Ref: {bi.sources[0]}")

    if report.pattern_interpretations:
        lines.append(f"\n{'─' * 72}")
        lines.append(f"  COMBINED PATTERN ANALYSIS ({len(report.pattern_interpretations)})")
        lines.append(f"{'─' * 72}")

        for p in report.pattern_interpretations:
            lines.append(f"\n  🔗 {p.pattern_name}")
            lines.append(f"     Reasoning: {p.clinical_reasoning[:200]}...")
            lines.append(f"     Suggests: {p.diagnosis_suggestion}")
            lines.append(f"     Workup: {' | '.join(p.recommended_workup[:3])}")
            if p.sources:
                lines.append(f"     Ref: {p.sources[0]}")

    lines.append(f"\n{'─' * 72}")
    lines.append(f"  LIFESTYLE RECOMMENDATIONS")
    lines.append(f"{'─' * 72}")
    for r in report.lifestyle_recommendations:
        lines.append(f"  • {r}")

    lines.append(f"\n{'─' * 72}")
    lines.append(f"  RECOMMENDED FOLLOW-UP TESTS")
    lines.append(f"{'─' * 72}")
    for t in report.follow_up_tests:
        lines.append(f"  • {t}")

    lines.append(f"\n{'─' * 72}")
    lines.append(f"  ⚕️  DISCLAIMER")
    lines.append(f"{'─' * 72}")
    lines.append(f"  {report.disclaimer}")

    lines.append(f"\n{'=' * 72}")
    return "\n".join(lines)


def report_to_json(report: ClinicalReport) -> str:
    """Serialize to JSON."""
    return json.dumps(asdict(report), indent=2, ensure_ascii=False)


# ================================================================
# CLI
# ================================================================

def main():
    import sys
    pdf_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.dirname(__file__)),
        "data", "sample_reports", "sample_report_01_cbc_lipid.pdf"
    )
    mode = sys.argv[2] if len(sys.argv) > 2 else "local"

    engine = ClinicalAnalysisEngine(mode=mode)
    report = engine.analyze_report(pdf_path)

    print(format_clinical_report(report))

    out_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "processed")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "clinical_report.json")
    with open(out_path, "w") as f:
        f.write(report_to_json(report))
    print(f"\n💾 {out_path}")


if __name__ == "__main__":
    main()
